import sys
import os
import time
from datetime import datetime, timedelta
import pandas as pd
import yfinance as yf
import gspread

# ---------------- LOG ---------------- #
def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)

# ---------------- CONFIG ---------------- #
SHARD_INDEX = int(os.getenv("SHARD_INDEX", "0"))
SHARD_SIZE = int(os.getenv("SHARD_SIZE", "500"))
START_ROW = SHARD_INDEX * SHARD_SIZE
END_ROW = START_ROW + SHARD_SIZE

# ---------------- GOOGLE SHEETS ---------------- #
def connect_sheets():
    gc = gspread.service_account("credentials.json")
    
    # Open the single spreadsheet workbook
    spreadsheet = gc.open("Tradingview Data Reel Experimental May")
    
    sh_source = spreadsheet.worksheet("Sheet5")
    sh_target = spreadsheet.worksheet("Sheet18")
    
    return sh_source, sh_target

def parse_date(date_str):
    """Normalizes various common sheet date formats into YYYY-MM-DD."""
    if not date_str:
        return None
    for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y"):
        try:
            return datetime.strptime(date_str.strip(), fmt)
        except ValueError:
            continue
    return None

def get_next_day_string(dt_obj):
    """Returns the next day as a string, required for yfinance end date boundary."""
    next_day = dt_obj + timedelta(days=1)
    return next_day.strftime("%Y-%m-%d")

# ---------------- MAIN ---------------- #
try:
    sheet_source, sheet_target = connect_sheets()
    
    # Read headers to locate dynamic column mappings dynamically
    headers = [h.strip().lower() for h in sheet_source.row_values(1)]
    
    # Match the specified columns: 'symbol', 'date1', and 'date2'
    symbol_col_idx = headers.index("symbol") + 1 if "symbol" in headers else 1
    date1_col_idx = headers.index("date1") + 1 if "date1" in headers else 7
    date2_col_idx = headers.index("date2") + 1 if "date2" in headers else 8
    
    # Extract column values
    symbol_list = sheet_source.col_values(symbol_col_idx)
    date1_list = sheet_source.col_values(date1_col_idx)
    date2_list = sheet_source.col_values(date2_col_idx)

    log(f"✅ Sheets mapped successfully. Columns found -> Symbol: Col {symbol_col_idx}, Date1: Col {date1_col_idx}, Date2: Col {date2_col_idx}")

except Exception as e:
    log(f"❌ Initialization/Sheet Reading error: {e}")
    sys.exit(1)

# Prepare target headers on Sheet18 if it's brand new/empty
try:
    if not sheet_target.row_values(1):
        sheet_target.append_row(["Symbol", "Target Date Label", "Datetime", "Open", "High", "Low", "Close", "Adj Close", "Volume"])
except Exception as e:
    log(f"⚠️ Header setup warning: {e}")

all_rows_payload = []

# Process rows within shard boundaries (skipping header row 0 in index calculation)
total_rows = len(symbol_list)
start_idx = max(1, START_ROW)
end_idx = min(END_ROW, total_rows)

for i in range(start_idx, end_idx):
    if i >= len(symbol_list):
        break
        
    raw_symbol = symbol_list[i].strip()
    if not raw_symbol:
        continue

    # Format symbol safely for Yahoo Finance (NSE requires .NS suffix)
    stock_symbol = raw_symbol if raw_symbol.endswith(".NS") else f"{raw_symbol}.NS"
    
    # Extract corresponding raw target dates
    raw_d1 = date1_list[i] if i < len(date1_list) else ""
    raw_d2 = date2_list[i] if i < len(date2_list) else ""
    
    target_dates = [("Date1", parse_date(raw_d1)), ("Date2", parse_date(raw_d2))]
    
    log(f"🔄 Processing row [{i+1}/{total_rows}] — Symbol: {stock_symbol}")
    
    for label, dt_obj in target_dates:
        if dt_obj is None:
            log(f"   ⚠️ Missing or invalid format for {label}, skipping.")
            continue
            
        start_str = dt_obj.strftime("%Y-%m-%d")
        end_str = get_next_day_string(dt_obj)
        
        log(f"   Downloading 1m data for {stock_symbol} on {start_str} ({label})...")
        
        try:
            df = yf.download(
                tickers=stock_symbol,
                start=start_str,
                end=end_str,
                interval="1m",
                progress=False
            )
            
            if df.empty:
                log(f"   ❌ No 1m data available for {stock_symbol} on {start_str} (Likely >30 days old or holiday)")
                continue
                
            # Flatten multi-index columns if generated by modern yfinance versions
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = df.columns.get_level_values(0)
                
            df.reset_index(inplace=True)
            
            # Format and convert dataframes into simple row arrays for Google Sheets upload
            for _, row_data in df.iterrows():
                # Convert timestamp object to readable string format
                ts = str(row_data['Datetime'])
                
                payload_row = [
                    stock_symbol,
                    label, # Tracking notation label ("Date1" or "Date2")
                    ts,
                    float(row_data['Open']),
                    float(row_data['High']),
                    float(row_data['Low']),
                    float(row_data['Close']),
                    float(row_data['Adj Close']) if 'Adj Close' in row_data else float(row_data['Close']),
                    int(row_data['Volume'])
                ]
                all_rows_payload.append(payload_row)
                
        except Exception as data_err:
            log(f"   ❌ Error executing yfinance fetch for {stock_symbol} [{label}]: {data_err}")
            
    # Regular safe intervals to avoid aggressive pooling rate limits
    time.sleep(1)

# Write output records iteratively using efficient multi-row append actions
if all_rows_payload:
    log(f"🚀 Pushing {len(all_rows_payload)} technical rows into Sheet18...")
    try:
        sheet_target.append_rows(all_rows_payload, value_input_option="RAW")
        log("✅ Upload successfully complete.")
    except Exception as upload_err:
        log(f"❌ Error uploading metrics array to target worksheet: {upload_err}")
else:
    log("⚠️ No new datasets fetched inside execution window metrics framework.")

log("🏁 DONE")
