import sys
import os
import time
from datetime import datetime, timedelta
import pandas as pd
import yfinance as yf
import gspread

# ---------------- LOG ---------------- #
def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)

# ---------------- CONFIG ---------------- #
SHARD_INDEX = int(os.getenv("SHARD_INDEX", "0"))
SHARD_SIZE = int(os.getenv("SHARD_SIZE", "500"))
START_ROW = SHARD_INDEX * SHARD_SIZE
END_ROW = START_ROW + SHARD_SIZE

# ---------------- GOOGLE SHEETS ---------------- #
def connect_sheets():
    gc = gspread.service_account("credentials.json")
    
    # Open the single spreadsheet workbook
    spreadsheet = gc.open("Tradingview Data Reel Experimental May")
    
    sh_source = spreadsheet.worksheet("Sheet5")
    sh_target = spreadsheet.worksheet("Sheet18")
    
    return sh_source, sh_target

# ---------------- MAIN ---------------- #
try:
    sheet_source, sheet_target = connect_sheets()
    
    # Read headers to locate dynamic column mappings dynamically
    headers = [h.strip().lower() for h in sheet_source.row_values(1)]
    
    # Match the specified columns: 'symbol'
    symbol_col_idx = headers.index("symbol") + 1 if "symbol" in headers else 1
    
    # Extract column values
    symbol_list = sheet_source.col_values(symbol_col_idx)

    log(f"✅ Sheets mapped successfully. Columns found -> Symbol: Col {symbol_col_idx}")

except Exception as e:
    log(f"❌ Initialization/Sheet Reading error: {e}")
    sys.exit(1)

# Prepare target headers on Sheet18 if it's brand new/empty
try:
    if not sheet_target.row_values(1):
        sheet_target.append_row(["Symbol", "Target Date Label", "Datetime", "Open", "High", "Low", "Close", "Adj Close", "Volume"])
except Exception as e:
    log(f"⚠️ Header setup warning: {e}")

all_rows_payload = []

# Process rows within shard boundaries (skipping header row 0 in index calculation)
total_rows = len(symbol_list)
start_idx = max(1, START_ROW)
end_idx = min(END_ROW, total_rows)

for i in range(start_idx, end_idx):
    if i >= len(symbol_list):
        break
        
    raw_symbol = symbol_list[i].strip()
    if not raw_symbol:
        continue

    # Format symbol safely for Yahoo Finance (NSE requires .NS suffix)
    stock_symbol = raw_symbol if raw_symbol.endswith(".NS") else f"{raw_symbol}.NS"
    
    log(f"🔄 Processing row [{i+1}/{total_rows}] — Symbol: {stock_symbol}")
    log(f"   Downloading last 30 days of 1m data for {stock_symbol}...")
    
    try:
        # Fetching maximum allowed historical 1-minute window (period="1mo")
        df = yf.download(
            tickers=stock_symbol,
            period="1mo",
            interval="1m",
            progress=False
        )
        
        if df.empty:
            log(f"   ❌ No 1m data available for {stock_symbol} in the last 30 days.")
            continue
            
        # Flatten multi-index columns if generated by modern yfinance versions
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
            
        df.reset_index(inplace=True)
        
        # Format and convert dataframes into simple row arrays for Google Sheets upload
        for _, row_data in df.iterrows():
            # Convert timestamp object to readable string format
            ts = str(row_data['Datetime'])
            
            payload_row = [
                stock_symbol,
                "Last 30 Days", # Hardcoded tracking notation label to preserve target schema
                ts,
                float(row_data['Open']),
                float(row_data['High']),
                float(row_data['Low']),
                float(row_data['Close']),
                float(row_data['Adj Close']) if 'Adj Close' in row_data else float(row_data['Close']),
                int(row_data['Volume'])
            ]
            all_rows_payload.append(payload_row)
            
    except Exception as data_err:
        log(f"   ❌ Error executing yfinance fetch for {stock_symbol}: {data_err}")
        
    # Regular safe intervals to avoid aggressive pooling rate limits
    time.sleep(1)

# Write output records iteratively using efficient multi-row append actions
if all_rows_payload:
    log(f"🚀 Pushing {len(all_rows_payload)} technical rows into Sheet18...")
    try:
        sheet_target.append_rows(all_rows_payload, value_input_option="RAW")
        log("✅ Upload successfully complete.")
    except Exception as upload_err:
        log(f"❌ Error uploading metrics array to target worksheet: {upload_err}")
else:
    log("⚠️ No new datasets fetched inside execution window metrics framework.")

log("🏁 DONE")
